style = "default"
align_assignment = true
align_matrix = true
align_struct_field = true
always_for_in = true
annotate_untyped_fields_with_any = false
format_docstrings = true
import_to_using = false
indent = 2
join_lines_based_on_source = true
margin = 100
pipe_to_function_call = false
remove_extra_newlines = true
separate_kwargs_with_semicolon = true
short_to_long_function_def = false
surround_whereop_typeparameters = true
trailing_comma = true
whitespace_in_kwargs = false
whitespace_ops_in_indices = false
whitespace_typedefs = false
